#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/environment'

@memberships = OrganizationMembership.administered
@memberships.each do |m|
  puts "#{m.user.name} <#{m.user.email}>"
end